### PR TITLE
javascript beginner project

### PR DESCRIPTION
**Pull request by shubhamnag14**

### CODE REVIEW

**Comment by pr4shan7** [comment]
Please describe your PR. @shubhamnag14

**Comment by pr4shan7** [comment]
After 3 days of inactivity, this PR will be marked `invalid` and will be closed. @shubhamnag14

**Comment by pr4shan7** [comment]
Waiting for your reply. @shubhamnag14

**Comment by shubhamnag14** [comment]
i have heen busy with some work....
this repository describe basic working of js

**Comment by shubhamnag14** [comment]
i thing i just missed to upload that file in the repo.
and i delete that file from lapi...wait will do new PR.

**Pull request closed without merging**
