### PR TITLE
Created Folder for adding C Code, with Examples

### PR DESCRIPTION
**Pull request by AakashJ2412**
Created a folder for adding favourite and useful example codes in C language, similar to the existing python folder.

In addition, added two example codes for bubble sort and number system base converter.

Thanks,
First-time contributor

### CODE REVIEW

**Comment by pr4shan7** [comment]
It would be even more helpful if you could explain, for example `bubblesort`, what the thing is and how it works using comments or a `markdown` or `txt` file (for example `bubblesort.md` or `bubblesort.txt`). @AakashJ2412

**Comment by AakashJ2412** [comment]
Thanks for letting me know, I'll make the changes and additions

**Comment by AakashJ2412** [comment]
Please review the changes and do inform if there is anything else to be edited.

Best Regards

**Comment by AakashJ2412** [comment]
Apologies for the error.

**Pull request merged**
