### PR TITLE
Added a new learning resourse

### PR DESCRIPTION
**Pull request by rakshathavasudev**
@pr4shan7 I have added a new web development learning resource in learning-resources.md.Please can you review it?Thanks

### CODE REVIEW

**Comment by Mayank-dev-commits** [comment]
Hi , can I add python program in the python folder

**Comment by rakshathavasudev** [comment]
@pr4shan7 Yes !

**Comment by Mayank-dev-commits** [comment]
I am new to git and github and i don't know why it is showing the following- This branch has conflicts that must be resolved

**Comment by pr4shan7** [comment]
> Hi , can I add python program in the python folder

Sure you can! @Mayank-dev-commits

**Comment by pr4shan7** [comment]
> I am new to git and github and i don't know why it is showing the following- This branch has conflicts that must be resolved

It simply means that the file which is to be modified via this PR has some new changes from other users which are in conflict with the proposed changes and must be resolved. @Mayank-dev-commits

**Pull request merged**
